import { $array } from "/transpiled/https://escad.dev/serial/$array.js";
import { $boolean } from "/transpiled/https://escad.dev/serial/$boolean.js";
import { $buffer } from "/transpiled/https://escad.dev/serial/$buffer.js";
import { $constant } from "/transpiled/https://escad.dev/serial/$constant.js";
import { $map } from "/transpiled/https://escad.dev/serial/$map.js";
import { $number } from "/transpiled/https://escad.dev/serial/$number.js";
import { $object } from "/transpiled/https://escad.dev/serial/$object.js";
import { $set } from "/transpiled/https://escad.dev/serial/$set.js";
import { $string } from "/transpiled/https://escad.dev/serial/$string.js";
import { registerType } from "/transpiled/https://escad.dev/serial/typeRegistration.js";
import { $unknown } from "/transpiled/https://escad.dev/serial/$unknown.js";
registerType("object", $object);
registerType("string", $string);
registerType("number", $number);
registerType("boolean", $boolean);
registerType("null", $constant(null));
registerType("undefined", $constant(undefined));
registerType("Uint8Array", $buffer);
registerType("Array", $array($unknown));
registerType("Map", $map($unknown, $unknown));
registerType("Set", $set($unknown)); // moderate

export * from "/transpiled/https://escad.dev/serial/$array.js";
export * from "/transpiled/https://escad.dev/serial/$boolean.js";
export * from "/transpiled/https://escad.dev/serial/$buffer.js";
export * from "/transpiled/https://escad.dev/serial/$constant.js";
export * from "/transpiled/https://escad.dev/serial/$json.js";
export * from "/transpiled/https://escad.dev/serial/$map.js";
export * from "/transpiled/https://escad.dev/serial/$number.js";
export * from "/transpiled/https://escad.dev/serial/$object.js";
export * from "/transpiled/https://escad.dev/serial/$record.js";
export * from "/transpiled/https://escad.dev/serial/$set.js";
export * from "/transpiled/https://escad.dev/serial/$string.js";
export * from "/transpiled/https://escad.dev/serial/$tuple.js";
export * from "/transpiled/https://escad.dev/serial/$unknown.js";
export * from "/transpiled/https://escad.dev/serial/BufferInfo.js";
export * from "/transpiled/https://escad.dev/serial/Serializer.js";
export * from "/transpiled/https://escad.dev/serial/typeRegistration.js";